# Generated by Django 4.2.14 on 2024-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
